name: Build & Deploy ProoFly

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # --- Getting the code ---
      - name: Checkout repo
        uses: actions/checkout@v3

      # --- Node.js ---
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # --- Frontend build ---
      - name: Install frontend dependencies
        run: npm install
        working-directory: ./frontend

      - name: Create frontend .env
        run: |
          rm -f ./.env
          echo "VITE_FIREBASE_API_KEY=${{ secrets.VITE_FIREBASE_API_KEY }}" > ./.env
          echo "VITE_FIREBASE_AUTH_DOMAIN=${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}" >> ./.env
          echo "VITE_FIREBASE_PROJECT_ID=${{ secrets.VITE_FIREBASE_PROJECT_ID }}" >> ./.env
          echo "VITE_FIREBASE_STORAGE_BUCKET=${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}" >> ./.env
          echo "VITE_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}" >> ./.env
          echo "VITE_FIREBASE_APP_ID=${{ secrets.VITE_FIREBASE_APP_ID }}" >> ./.env
          echo "VITE_FIREBASE_MEASUREMENT_ID=${{ secrets.VITE_FIREBASE_MEASUREMENT_ID }}" >> ./.env

      - name: Build frontend
        run: npm run build
        working-directory: ./frontend

      # --- Backend setup ---
      - name: Install backend dependencies
        run: npm install
        working-directory: ./backend

      - name: Decode Firebase Admin JSON
        run: |
          echo ${{ secrets.FIREBASE_ADMIN_JSON_BASE64 }} | base64 --decode > ./backend/serviceAccount.json

